name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Se activa cada vez que haces "git push" a la rama main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto (Build)
        run: npm run build

      - name: Subir a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Le decimos que suba la carpeta dist que se acaba de crear

      - name: Desplegar
        uses: actions/deploy-pages@v4